### ISSUE TITLE
Missing `sender` when sending a transaction should send a nicer message.

### ISSUE THREAD

**Issue by pandadefi** [ApeWorX/ape#646] opened 2022-04-08 14:49 UTC
### Environment information

It will stop with the error:

```
ERROR: (ConversionError) No conversion registered to handle 'None'.
```

**Comment by unparalleled-js** [comment] 2022-04-08 17:23
Can I have more detail on the type of transaction you are making?
When I tried to reproduce, I get different (more helpful) errors. There are many ways to transact in Ape though!

Thank you:)

**Comment by unparalleled-js** [comment] 2022-04-08 18:38
I would like to know:

a.) The type of account uses (impersonated, test account, or normal account like a keyfile account)?
b.) The type of transaction, e.g. a deploy, a type 2 method call, a transfer, etc.

**Comment by fubuloubu** [comment] 2022-04-08 19:04
> I would like to know:
> 
> a.) The type of account uses (impersonated, test account, or normal account like a keyfile account)?
> b.) The type of transaction, e.g. a deploy, a type 2 method call, a transfer, etc.
> 

It's a vyper mutable function with default parameters

**Comment by fubuloubu** [comment] 2022-04-08 19:05
https://github.com/yearn/yearn-vaults/blob/1f8a4111725134caa39f07cd289b5d2d7a0ee17a/contracts/Vault.vy#L266

With args

vault.initialize(token, account, account, "test", "test", account, account)

**Comment by unparalleled-js** [comment] 2022-04-08 21:16
I get the error:

```
SignatureError: The transaction is not signed.
```

**Comment by unparalleled-js** [comment] 2022-04-08 23:07
Okay I was able to reproduce by using an `ImpersonatedAccount`
Standby for bugfix!

**Comment by unparalleled-js** [comment] 2022-04-09 00:22
Turns out this is a bug in hardhat.
I have a PR fix for it here: https://github.com/ApeWorX/ape-hardhat/pull/44

**Comment by unparalleled-js** [comment] 2022-04-12 16:29
Fixed in https://github.com/ApeWorX/ape-hardhat/pull/44

**Closed by unparalleled-js** 2022-04-12 16:29 UTC
Labels: bug
