### ISSUE TITLE
feature: import wallets/accounts via seed phrase

### ISSUE THREAD

**Issue by Ninjagod1251** [ApeWorX/ape#953] opened 2022-08-08 18:51 UTC
### Overview

Provide a simple overview of what you wish to see added. Please include:

[account import](https://docs.apeworx.io/ape/stable/commands/accounts.html?highlight=import)

We talk about a way to import account via private key. 

What about import via seed phrase via cli and python script?

### Specification

I want to be able import without breaking any security features an account via seed phrase.

We should store the use the key and fetch the account and not save the seed phrase in clear text or not at all.

### Dependencies

Can we link the script of the seed phrase in the ape-config.yaml?

@unparalleled-js @fubuloubu

**Comment by unparalleled-js** [comment] 2022-08-08 19:01
Duplicate of https://github.com/ApeWorX/ape/issues/259

**Closed by unparalleled-js** 2022-08-08 19:01 UTC
Labels: category: feature

**Comment by fubuloubu** [comment] 2022-08-09 00:39
Also, quick note: definitely do not pull this info from the config file
