### ISSUE TITLE
Allow folders inside the script folder to be scripts

### ISSUE THREAD

**Issue by PatrickAlphaC** [ApeWorX/ape#929] opened 2022-07-31 19:22 UTC
### Overview

Inside your scripts folder, create a new folder called `new_folder`, and add a script called `run_script.py` in there. Running `tree .` you should see something like:

```
.
├── README.md
├── ape-config.yaml
├── contracts
├── scripts
   ├── new_folder
      └── run_script.py
```

In that, add the code:

```
def main():
  print("What's up")
```

Then try to run that script:

```
ape run scripts/new_folder/run_script.py
```

And it won't print `What's up`

**Comment by fubuloubu** [comment] 2022-08-01 01:01
Does it have a failure?

Also, can you try adding `__init__.py` files inside both directories?

**Comment by PatrickAlphaC** [comment] 2022-08-04 18:43
Yes and Yes

```
Error: No such command 'scripts/new_folder/run_script.py'.
```

Or

```
Error: No such command 'run_script'.
```

**Comment by fubuloubu** [comment] 2022-08-04 22:41
Can confirm this. Root cause is it doesn't walk the full directory right now in https://github.com/ApeWorX/ape/blob/main/src/ape_run/_cli.py#L115

**Comment by NotPeopling2day** [comment] 2022-08-08 13:26
@PatrickAlphaC is https://github.com/ApeWorX/ape/issues/804 a duplicate?

**Comment by PatrickAlphaC** [comment] 2022-08-13 02:30
@NotPeopling2day yep. I'm idiot.

**Comment by unparalleled-js** [comment] 2022-09-27 17:51
Closing as duplicate

**Closed by unparalleled-js** 2022-09-27 17:51 UTC
Labels: category: bug
