### ISSUE TITLE
Interactive command doesn't happen if script execution fails

### ISSUE THREAD

**Issue by pandadefi** [ApeWorX/ape#645] opened 2022-04-08 13:19 UTC
### What went wrong?

Create a script that has some issues (my script was missing the `sender` parameter)
execute it with the `-i` option: ape run -i scripts/deploy.py main

it will not open the interactive command

**Comment by unparalleled-js** [comment] 2022-04-08 21:08
We know about this one, it is unfortunate and will fix soon!
Closing as duplicate of https://github.com/ApeWorX/ape/issues/581

**Comment by unparalleled-js** [comment] 2022-04-08 21:44
Realizing this is a little different since this is not opening the console at all, but will fix both at once so reopening till then!

**Comment by unparalleled-js** [comment] 2022-04-08 22:33
Ha, okay realized these are two separate issue.. #645 is fixed on the linked PR!
#645 seems to happen on hardhat / infura, etc, but not on the `eth-tester` provider... Will try to fix that one next

**Closed** 2022-04-28 19:09 UTC
Labels: bug
